
tasks:
  - init: |
      echo 'TODO: build project'
    command: |
      echo 'TODO: start app'

ports:
  - port: 8000
    onOpen: open-preview

# jetbrains:
#   intellij:
#     plugins:
#       - com.haulmont.jpab
#       - org.intellij.plugins.hcl
#     prebuilds:
#       version: both
vscode:
  extensions:
    - GitHub.github-vscode-theme
    - hashicorp.terraform
